version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user
hooks:
  AfterInstall:
    - location: pullimage.sh
      timeout: 100
  ApplicationStart:
    - location: applicationstart.sh
      timeout: 100
